[project]
name = "ai-skin-specialist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepgram-sdk>=7.7.0",
    "fastapi>=0.141.1",
    "flask>=3.1.0",
    "flask-cors>=6.0.0",
    "gradio>=6.25.0",
    "groq>=1.6.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn>=0.52.4",
]

[project.scripts]
ai-skin-specialist = "ai_skin_specialist:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
